import { useState, useEffect, useCallback } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { getMarkdownContent } from '../../services/markdownService';
import { RefreshCw } from '../icons/index';

const MethodologyReport = ({ assessmentId }) => {
  const [content, setContent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchReport = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getMarkdownContent(assessmentId, 'methodology.md');
      const text = data?.content || '';
      // Strip the default template header — only show if AI has written real content
      const isTemplate =
        text.trim() === '' ||
        (text.includes('Generated by NEMESIS AI') && text.split('\n').filter(l => l.trim()).length <= 4);
      setContent(isTemplate ? null : text);
    } catch {
      setContent(null);
    } finally {
      setLoading(false);
    }
  }, [assessmentId]);

  useEffect(() => {
    fetchReport();
  }, [fetchReport]);

  return (
    <div className="border border-gray-200 dark:border-neutral-700 rounded bg-white dark:bg-neutral-800">
      {/* Header */}
      <div className="px-4 py-3 border-b border-gray-200 dark:border-neutral-700 bg-gray-50 dark:bg-neutral-900 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-sm font-semibold text-gray-800 dark:text-neutral-100">
            Methodology Report
          </span>
          <span className="text-xs text-gray-400 dark:text-neutral-500 font-mono">
            methodology.md
          </span>
        </div>
        <button
          onClick={fetchReport}
          className="p-1 hover:bg-gray-200 dark:hover:bg-neutral-700 rounded text-gray-400 dark:text-neutral-500 hover:text-gray-600 dark:hover:text-neutral-300 transition-colors"
          title="Refresh"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {/* Content */}
      <div className="p-4">
        {loading ? (
          <div className="py-8 text-center text-sm text-gray-400 dark:text-neutral-500">
            Loading...
          </div>
        ) : content ? (
          <div className="border border-gray-200 dark:border-neutral-700 rounded bg-white dark:bg-neutral-900 p-4 prose prose-sm prose-neutral dark:prose-invert max-w-none">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                // pre wraps fenced code blocks (```...```)
                pre: ({ children }) => (
                  <pre className="bg-neutral-900 dark:bg-neutral-950 text-neutral-100 p-3 rounded overflow-x-auto text-xs my-2 font-mono">
                    {children}
                  </pre>
                ),
                // code is inline when it has no language className
                code({ node, className, children, ...props }) {
                  const isBlock = Boolean(className);
                  return isBlock ? (
                    <code className={`font-mono ${className || ''}`} {...props}>{children}</code>
                  ) : (
                    <code className="bg-neutral-100 dark:bg-neutral-800 text-neutral-800 dark:text-neutral-200 px-1 py-0.5 rounded text-xs font-mono" {...props}>
                      {children}
                    </code>
                  );
                },
                h1: ({ children }) => <h1 className="text-xl font-bold text-neutral-900 dark:text-neutral-100 mb-3 mt-4 first:mt-0">{children}</h1>,
                h2: ({ children }) => <h2 className="text-lg font-semibold text-neutral-800 dark:text-neutral-100 border-b border-neutral-200 dark:border-neutral-700 pb-1 mb-3 mt-6 first:mt-0">{children}</h2>,
                h3: ({ children }) => <h3 className="text-base font-semibold text-neutral-700 dark:text-neutral-200 mb-2 mt-4 first:mt-0">{children}</h3>,
                h4: ({ children }) => <h4 className="text-sm font-semibold text-neutral-600 dark:text-neutral-300 mb-1 mt-3">{children}</h4>,
                p: ({ children }) => <p className="text-sm text-neutral-700 dark:text-neutral-300 leading-relaxed mb-2">{children}</p>,
                ul: ({ children }) => <ul className="list-disc pl-5 space-y-1 text-sm text-neutral-600 dark:text-neutral-300 mb-3">{children}</ul>,
                ol: ({ children }) => <ol className="list-decimal pl-5 space-y-1 text-sm text-neutral-600 dark:text-neutral-300 mb-3">{children}</ol>,
                li: ({ children }) => <li className="leading-relaxed">{children}</li>,
                hr: () => <hr className="border-neutral-200 dark:border-neutral-700 my-5" />,
                strong: ({ children }) => <strong className="font-semibold text-neutral-800 dark:text-neutral-200">{children}</strong>,
                em: ({ children }) => <em className="italic text-neutral-600 dark:text-neutral-400">{children}</em>,
                blockquote: ({ children }) => <blockquote className="border-l-4 border-neutral-300 dark:border-neutral-600 pl-4 italic text-neutral-500 dark:text-neutral-400 text-sm my-3">{children}</blockquote>,
                table: ({ children }) => (
                  <div className="overflow-x-auto my-4">
                    <table className="w-full text-sm border-collapse border border-neutral-200 dark:border-neutral-700">{children}</table>
                  </div>
                ),
                thead: ({ children }) => <thead className="bg-neutral-100 dark:bg-neutral-800">{children}</thead>,
                tbody: ({ children }) => <tbody className="divide-y divide-neutral-200 dark:divide-neutral-700">{children}</tbody>,
                tr: ({ children }) => <tr className="hover:bg-neutral-50 dark:hover:bg-neutral-800/50">{children}</tr>,
                th: ({ children }) => <th className="text-left px-3 py-2 text-xs font-semibold text-neutral-700 dark:text-neutral-300 border border-neutral-200 dark:border-neutral-700">{children}</th>,
                td: ({ children }) => <td className="px-3 py-2 text-xs text-neutral-600 dark:text-neutral-400 border border-neutral-200 dark:border-neutral-700 align-top">{children}</td>,
              }}
            >
              {content}
            </ReactMarkdown>
          </div>
        ) : (
          <div className="py-10 text-center space-y-2">
            <p className="text-sm text-gray-500 dark:text-neutral-400">
              No methodology report yet.
            </p>
            <p className="text-xs text-gray-400 dark:text-neutral-500">
              At the end of the engagement, ask the AI to generate one —<br />
              it will explain its reasoning, tools used, and full discovery summary.
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default MethodologyReport;
